spring.application.name=pharmacy-backend

# Database Configuration
spring.datasource.url=jdbc:mysql://yamanote.proxy.rlwy.net:32347/railway
spring.datasource.username=root
spring.datasource.password=CmCyihlTTdVXPRqWXBeyNGWyqulsEhkz
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server Port
server.port=8080